### ISSUE TITLE
スマホサイズ時のロゴの調整

### ISSUE THREAD

**Issue by kurefa** [codeforsaga/covid19#10]
## 改善詳細 / Details of Improvement
- xxxx(できるだけ簡潔に/as concise as possible)
スマホサイズ時のロゴの調整
## スクリーンショット / Screenshot

![名称未設定 1](https://user-images.githubusercontent.com/7993820/78623686-2d2b7500-78c3-11ea-90bc-4edd22b4c342.png)

## 期待する見せ方・挙動 / Expected behavior
- xxxx(できるだけ簡潔に/as concise as possible)
![名称未設定 2](https://user-images.githubusercontent.com/7993820/78623778-521fe800-78c3-11ea-9f30-f849cf8ecaf6.png)
・サイズを小さくする
・スマホ用のサイズのアイコンを表示する

## 動作環境・ブラウザ / Environment
-  Windows
- Chrome

**Comment by msx2mac** [comment]
着手したいと思います。
福岡版のリポジトリを確認したところ、別画像ではなくメディアクエリによるwidth変更で対応されていました。
https://github.com/Code-for-Fukuoka/covid19-fukuoka/blob/development/components/SideNavigation.vue
この方向で実装したいと思います。
