### ISSUE TITLE
ステージング・本番環境記載の削除について

### ISSUE THREAD

**Issue by msx2mac** [codeforsaga/covid19#12]
## 改善詳細 / Details of Improvement
READMEの「ステージング・本番環境への反映」について、リンク先がフォーク元になっています。

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/5077109/78732468-ad161580-797d-11ea-874d-9cb2d2b94c07.png)

## 期待する見せ方・挙動 / Expected behavior
こちらのリポジトリで各環境の情報が見当たりませんでしたので、非公開であれば削除します。

## 起こっている問題の再現手段 / Steps to Reproduce
chromeにて https://github.com/codeforsaga/covid19/blob/development/README.md へアクセスし確認しました。

## 動作環境・ブラウザ / Environment
- 依存なし

**Comment by ktouda-lml** [comment]
こちらもご指摘ありがとうございます。
「ステージング・本番環境への反映」については
修正しておりますのでご連絡いたします。

**Comment by msx2mac** [comment]
LGTMです！
ありがとうございました
