### ISSUE TITLE
robots.txtでのDisallow指定について

### ISSUE THREAD

**Issue by msx2mac** [codeforsaga/covid19#14]
## 起こっている問題 / The Problem
production環境でのrobots.txtにおいてDisallow指定されており、クローラーで除外されています。

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/5077109/78742353-be1f5080-7996-11ea-8882-e051d5105d67.png)

## 期待する見せ方・挙動 / Expected Behavior
develop.ymlで指定されているrobots.txtが、productionへのdeploy時にそのまま配置されていると思われます。
production環境では別途robots.txtを準備するか、deploy時に書き換えるべきだと思います。

## 起こっている問題の再現手段 / Steps to Reproduce
chromeにて https://stopcovid19.code4saga.org/robots.txt へアクセスし確認しました。

## 動作環境・ブラウザ / Environment
- 依存なし

**Comment by ktouda-lml** [comment]
ありがとうございます
取り急ぎdevelop.ymlでのrobot.txtのビルド部分の修正を行い
サイト側に反映しておりますので連絡いたします。

**Comment by msx2mac** [comment]
@ktouda-lml 
ありがとうございます！

**Comment by msx2mac** [comment]
@ktouda-lml 
後で対応されると思いますが、今回の修正ではdevelopment環境がインデックスされる可能性があるため、一応openのままにしておきます。
https://github.com/tokyo-metropolitan-gov/covid19/issues/198

もしdevelopment環境自体、ACL等でクロール制限されている、もしくは閉じられた環境であれば、closeしていただければと思います。

**Comment by ktouda-lml** [comment]
ご指摘ありがとうございます。承知しました。
development環境はクローズドな環境で確認しておりクロールは制限されておりますので
大丈夫です。
こちらのissueをcloseさせていただきますのでよろしくお願いいたします。
