### ISSUE TITLE
googleでの再クロール申請について

### ISSUE THREAD

**Issue by msx2mac** [codeforsaga/covid19#24]
## 改善詳細 / Details of Improvement
- 以前robots.txtにてDisallow設定していた影響か、未だにgoogleにて"佐賀 新型コロナ対策サイト" などと検索してもヒットしません。
個人的には、県民に知ってもらう事が重要と考えますので、再クロール申請を行っていただければありがたいです。

**Comment by ktouda** [comment]
ありがとうございます。
取り急ぎsearch consoleの設定を行いました。
一旦こちらでクローリング状況や設定を行いたいと思います。

**Comment by msx2mac** [comment]
@ktouda ありがとうございます！

**Comment by ktouda** [comment]
その後、確認しまして
先日設定した内容ではrobots.txtでブロックされているようでした。
robots.txtを見直し再クロールの申請を行いましたので
少し様子を見たいと思います。

**Comment by ktouda** [comment]
今朝時点でsearch consoleで確認しましたところ
「佐賀県 コロナ」や「stopcovid19」などの検索ワードでヒットしていることが
確認できましたのでご連絡いたします。
（「佐賀県 コロナ」では私の端末で検索結果の2ページ目に表示されてました。）

**Comment by msx2mac** [comment]
確認できました。ありがとうございました！
