### ISSUE TITLE
The script has an unsupported MIME type ('text/html'). エラーが発生する

### ISSUE THREAD

**Issue by msx2mac** [codeforsaga/covid19#27]
## 起こっている問題 / The Problem
- chromeにて公開サイト表示時に、デベロッパーツールを表示すると、"The script has an unsupported MIME type ('text/html')." が表示されます。

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/5077109/78967469-87d00580-7b3d-11ea-93e4-69037ace5711.png)

## 期待する見せ方・挙動 / Expected Behavior
- エラー発生の抑止
sw.jsの読み込みで発生しているのではないかと考えています。
.htaccess等でAddTypeをすることで改善するかもしれません。

## 起こっている問題の再現手段 / Steps to Reproduce
1. chromeにて デベロッパーツールを開きます。
2. https://stopcovid19.code4saga.org/ へアクセスします。
3. consoleに当該エラーが表示されます。

## 動作環境・ブラウザ / Environment
- Windows
- Chrome 81

**Comment by ktouda** [comment]
ありがとうございます。
.htaccess側に
AddType application/javascript .js 
AddCharset utf-8 .js
を追記設定しました。

**Comment by msx2mac** [comment]
@ktouda LGTMです！ありがとうございました！
