### ISSUE TITLE
佐賀県のコロナ公式ページへのリンクに切り替える

### ISSUE THREAD

**Issue by TakuyaKinoshita** [codeforsaga/covid19#3]
## 問題点
- 東京からForkしたものなので,佐賀県庁の公式のコロナ対策ページのリンクに切り替える 
## 差し替え後URL
[https://www.pref.saga.lg.jp/list04342.html](url)

**Comment by horiyo** [comment]
[components/SideNavigation.vue を修正](https://github.com/codeforsaga/covid19/commit/70d741fd3ac65f3d9d666b3c2c8e6a7e162bb9e9#diff-88933f3e0716e9e2ec2ffa68867e24a6)した
