### ISSUE TITLE
ファビコンの背景透過

### ISSUE THREAD

**Issue by kurefa** [codeforsaga/covid19#33]
## 改善詳細 / Details of Improvement
-ファビコンの背景を透明にする

## スクリーンショット / Screenshot
![1](https://user-images.githubusercontent.com/7993820/79195063-9cc3d600-7e68-11ea-87f6-a3e6da9e02dd.png)

## 期待する見せ方・挙動 / Expected behavior
![2](https://user-images.githubusercontent.com/7993820/79195080-a2b9b700-7e68-11ea-9aa5-5aa7959c5400.png)

## 動作環境・ブラウザ / Environment
- Windows 
- Chrome

**Comment by msx2mac** [comment]
着手したいと思います。
