### ISSUE TITLE
県発表における陽性者分類の増

### ISSUE THREAD

**Issue by horiyo** [codeforsaga/covid19#35]
## 起こっている問題 / The Problem
- 県発表における陽性者分類の増
陽性者の分類に、「県外」および「ホテル宿泊」が追加された。

## スクリーンショット / Screenshot
- 自明

## 期待する見せ方・挙動 / Expected Behavior
- グラフデザイン変更か？

## 起こっている問題の再現手段 / Steps to Reproduce
- 自明

## 動作環境・ブラウザ / Environment
- any

**Comment by mgr-kb** [comment]
@horiyo cc: @ktouda 
お疲れ様です。
こちらのissueについて対応してみましたので、お手すきの際にご確認いただけますでしょうかmm
https://github.com/codeforsaga/covid19/pull/36

疑問点等ございましたらご連絡くださいmm
