### ISSUE TITLE
検査陽性者の状況グラフのレイアウトが窮屈なので改善したい

### ISSUE THREAD

**Issue by mgr-kb** [codeforsaga/covid19#37]
## 改善詳細 / Details of Improvement
- https://github.com/codeforsaga/covid19/issues/35 の改善に伴い、検査陽性者の状況グラフの横幅が窮屈になったため、広く見せられるようにしたい

## スクリーンショット / Screenshot

![スクリーンショット 2020-05-03 13 59 04](https://user-images.githubusercontent.com/22042083/80899057-51edfd80-8d46-11ea-8b73-00a0dce6ac50.png)

## 期待する見せ方・挙動 / Expected behavior
- ゆとりを持たせたレイアウトとしたい

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by horiyo** [comment]
分類枠「入院中」の細分類「軽症・中等症」「重症」は佐賀県の場合発表されていないので削れます。
