### ISSUE TITLE
最新のお知らせの表示件数を切り替えられるようにしたい

### ISSUE THREAD

**Issue by mgr-kb** [codeforsaga/covid19#8]
## 改善詳細 / Details of Improvement
- 現状だと、お知らせが溜まるにつれてサイトの表示が縦長になっていくので、表示件数(or 表示期間)を設定することでお知らせの表示件数を制限できればと思っています。

## スクリーンショット / Screenshot
現状の表示
<img width="1440" alt="before" src="https://user-images.githubusercontent.com/22042083/78574964-b01de280-7865-11ea-9066-18c844706265.png">

お知らせが縦長になっていくため、ファーストビューでは検査状況などの情報が入ってきづらくなる。

## 期待する見せ方・挙動 / Expected behavior
- 以下のように表示件数(or表示期間)を設定できるようにすることで、スッキリ見せられるようにする。
- デフォルトは3件程度にするなど。
<img width="1440" alt="after" src="https://user-images.githubusercontent.com/22042083/78578852-0d686280-786b-11ea-8874-c9128306d6fe.png">

補足
- 純粋にnews.jsonからnewsを削除するでも良い気はしていますが、過去のnewsを見るケースもあるかもしれないので、こちらのご提案をさせていただきました。

## 動作環境・ブラウザ / Environment
以下の環境で確認しています。
- macOS
- Chrome

**Comment by mgr-kb** [comment]
もしも問題なければこちらは手元では対応済のため、すぐにプルリクを出すことが可能ですmm

**Comment by msx2mac** [comment]
現状見づらくなっているので、是非実装をお願いしたいです！
しかし、反応ありませんね…

**Comment by mgr-kb** [comment]
@msx2mac 
ご確認ありがとうございます！
どなたのGoが出れば良いかはわかりませんが、プルリクはいつでも出せる状態なので、作るだけ作ってしまおうかなと思います...!

> しかし、反応ありませんね…

先ほど、slackのチャンネルの方で通知に関する提案をしてみましたので、それを承認いただければキャッチアップがしやすくなるかもです...!
