### ISSUE TITLE
サイドメニューの余白幅が詰まっている

### ISSUE THREAD

**Issue by mgr-kb** [codeforsaga/covid19#9]
## 改善詳細 / Details of Improvement
- 現在のサイドメニューだと、「新型コロナウイルス感染症について」のメニューのみ、余白がなく詰まって見えるようになっています。
- 動きとしては問題ないと思いますが、他のメニューとのバランスも考えて、余白に余裕を持たせた方が良いかと思いました。

## スクリーンショット / Screenshot
<img width="287" alt="スクリーンショット 2020-04-07 1 07 36" src="https://user-images.githubusercontent.com/22042083/78579769-6258a880-786c-11ea-9b65-5a6e32e291b1.png">

## 期待する見せ方・挙動 / Expected behavior
以下のいずれかの対応で解決するかと思います。
- アイコンを取り除く
- スタイルを調整する(もしくは全メニューにアイコンを付与するなど)

前者がシンプルで一番わかりやすいかと思っております。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by msx2mac** [comment]
フォーク元の東京都のリポジトリではすでに解決しているようですが、SideNavigation.vueに大幅に手を入れられており、フォーク時からは構造自体が変わっているようです。
とりあえず、$hugeにブレイクした際に、max-widthを調整するようにしてみました。
development環境が非公開なので、とりあえずスクリーンショットを貼っておきます。

変更前
![image](https://user-images.githubusercontent.com/5077109/78961091-2737cd00-7b2b-11ea-862a-d12e16d1408c.png)

変更後
![image](https://user-images.githubusercontent.com/5077109/78961096-2bfc8100-7b2b-11ea-83e4-a50cd402a925.png)

「アイコンを取り除く」案と合わせてご検討いただければと思います。

**Comment by mgr-kb** [comment]
@msx2mac 
ご確認・ご対応ありがとうございますー！

他のメニューリストでアイコンがないという点が気になる点ではありますが、ひとまずは問題ないかと思います！

**Comment by msx2mac** [comment]
@mgr-kb
ありがとうございます！
そうなんですよね。他県の物だと、そもそもメニュー自体に
- 県内の感染動向
- 感染症が心配なときに

がアイコン付きであるので、これを追加したらもう少しバランス良くなる気がします。
当リポジトリのソースにもコメントアウトされて残っているので、意図されて削除されているのかもしれませんが…
